---
language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
install:
  # mecab
  - curl -O http://mecab.googlecode.com/files/mecab-0.996.tar.gz && tar xf mecab-0.996.tar.gz
  - pushd mecab-0.996 && ./configure && make && sudo make install && popd
