---
language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
env:
  - "mecab_version=0.996"
  - "mecab_version=0.98"
  - "mecab_version=0.96"
install:
  # mecab
  - curl -O http://mecab.googlecode.com/files/mecab-${mecab_version}.tar.gz && tar xf mecab-${mecab_version}.tar.gz
  - pushd mecab-${mecab_version} && ./configure && make && sudo make install && popd
  - sudo ldconfig
  # bundler
  - bundle install
